// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';

import config from './src/config/index.js';

const isDirectNeeded = process.argv.some(
  arg => arg === 'migrate' || arg === 'push' || arg === 'reset',
);

export default defineConfig({
  schema: './prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    ...(isDirectNeeded ? { url: config.db.directUrl } : { url: config.db.url }),
  },
});
